image:
  repository: nls44/myproject-frontend
  tag: "production-362bfa3" # 2022-11-16T23:32:06Z https://circleci.com/gh/nls44/myproject-frontend/4

containerPort: 80

replicaCount: 1

deployment:
  env:
    normal:
      PROJECT_ENV: "production"

service:
  type: LoadBalancer
  name: "frontend-production"
