image:
  repository: tonoid/myproject-api
  tag: "production-cb22b5f" # 2022-11-16T23:28:41Z https://circleci.com/gh/nls44/myproject-api/4

containerPort: 80

replicaCount: 2

deployment:
  env:
    normal:
      PROJECT_ENV: "production"
      MY_VARIABLE: "2"