cronJobs:
  cronjob-run-action:
    schedule: "0 */6 * * *" # every 6 hours
    image: tonoid/myproject-api:production-cb22b5f # 2022-11-16T23:28:41Z https://circleci.com/gh/nls44/myproject-api/4
    cmd: "node ./tasks/runAction.js"

jobs: {}

env:
  normal:
    PROJECT_ENV: "production"
